;;; Copyright (c) 2021-2022 Ufasoft  http://ufasoft.com  mailto:support@ufasoft.com,  Sergey Pavlov  mailto:dev@ufasoft.com
;;;
;;; SPDX-License-Identifier: MIT

;;; BK-0010.01 Keyboard codes

$K.LE	= 10	; Left key
$K.NL	= 12	; Left key
$K.TAB	= 15
$K.RUS	= 16
$K.LAT	= 17
$K.BC	= 23	; BC key (return previous string)
$K.DEL	= 26	; !<--
$K.INS	= 27	; !-->
$K.BS	= 30	; Backspace
$K.RI	= 31	; Right key
$K.UP	= 32	; Up key
$K.DO	= 33	; Down key
$K.RPT	= 201	; Repeat
$K.BLK	= 204	; Block editor
$K.STP	= 240	; Step
