;;; Copyright (c) 2021 Ufasoft  http://ufasoft.com  mailto:support@ufasoft.com,  Sergey Pavlov  mailto:dev@ufasoft.com
;;;
;;; SPDX-License-Identifier: MIT

;;; Configuration definitions for BkLisp

BK10.01	= 1		; Define for BK-0010.01 conditional compilation
; C$FULL = 1		; If non-defined - Reduced subset of Common Lisp
; C$MVAL = 1		; BkLisp don't dupport multiple values
; C$MACR = 1		; No macros

C$MDAR 	= 1		; Multi-dimensional arrays
C$RAD40	= 1		; use RADIX-40 Symbol encoding
